### ISSUE TITLE
german accounting

### ISSUE THREAD

**Issue by pniederlag** [OCA/l10n-germany#15]
Is the core-addon ln10_de with the german accounting part of this initiative?

Would it make sense to add it here?

**Comment by tv-openbig** [comment]
Hello Peter, l10n_de is a core module.

Regarding your issue with default settings for the digits and the taxes used 
by the installation wizard of accounting, i have created a PR here:
https://github.com/odoo/odoo/pull/8803

You can find more informations, how to contribute on the OCA website:
https://odoo-community.org/project/local-germany-maintainers-61

The slideshow or also the following website explains how to contribute:
https://odoo-community.org/page/Contribute

**Comment by pniederlag** [comment]
big thx, so we can close this ticket
