### ISSUE TITLE
[14.0] datev_export_xml double entries in xml

### ISSUE THREAD

**Issue by david-fleischmann** [OCA/l10n-germany#161]
## Module
 datev_export_xml

## Describe the bug
The datev exort is under certain circumstances having double entries for invoice_item_list

## To Reproduce
Trigger xml export of an invoice with configuration "tax_excluded" so only net values are shown in invoice lines.
In the XML file you will have the invoice_item_list entries twice:

![image](https://github.com/OCA/l10n-germany/assets/73656049/b31aa59a-3fd1-4ff3-a4ba-aea72b6bd72c)

In my opinion the error is in line 60 not using t-elif, because if in line 51 t-if condition is met it will be resulting in printing again the invoice_item_list from L59 
![image](https://github.com/OCA/l10n-germany/assets/73656049/2037a001-d684-4c43-99b5-2edbeeae0e4b)

**Expected behavior**
having invoice_item_list just once per line in the xml export.

**Comment by fkantelberg** [comment]
Thanks for the notification. I added the commit to the already open PRs #158 #159 and #160 because it's just easier for me than creating more PRs but I can split it into different PRs if you insist.

**Comment by david-fleischmann** [comment]
@fkantelberg fine for me, thank you! I will close the issue then :)
