### ISSUE TITLE
German companies needs two kinds of VAT number

### ISSUE THREAD

**Issue by satriani-vai** [OCA/l10n-germany#32]
As I already wrote, the german company need two tax numders.
[St.-Nr.](https://de.wikipedia.org/wiki/Steuernummer) eg. 21/815/08150  and [Steuer-IdNr.](https://de.wikipedia.org/wiki/Steuerliche_Identifikationsnummer) eg. DE123456789
The module l10n_de_steuernummer dose not help in this case, because we need two fields for two kinds of the VAT in Germany.

**Comment by pedrobaeza** [comment]
I don't agree. We have several German companies, and they only need one or the other, not both.

**Comment by satriani-vai** [comment]
Yes, sometimes one of them is enough. Here in Germany, you usually enter both into the bill, so everything works fine. When the St.-Nr. is abolished is still unknown.
I have my own module, so I have both fields. So I do not care, but for the others it would be helpful option :wink:

**Comment by OSevangelist** [comment]
Guys the point here is that some official forms still require the specific German number St.-Nr. especially if you want to interface with third party software but teh Steuer-ldNr. is the European standard. I am 100% with @pedrobaeza on that matter as this is something that will die over time anyway and who every really needs that can to it in an easy tweak him / herself but it has not the level of generalizability anymore to be included in th German Localization (if we can even call it as such ;-)

**Comment by pedrobaeza** [comment]
I think that's the point: for current localization status, what you need is to be able to issue an invoice with that old number, and for that it's simpler to use the same VAT field and allows to write it making the check to be correct. When a new localization module that forcefully requires always the old one arrives, then we can add the extra field for that one.

**Comment by satriani-vai** [comment]
> When a new localization module that forcefully requires always the old one arrives, then we can add the extra field for that one.

That's a good idea :smiley:

**Comment by tbaden** [comment]
I think the issue can be closed. No use case in a year and the probability is getting lower and lower.
