### ISSUE TITLE
[12.0] Format issues with tax lines in l10n_de_tax_statement (v2019)

### ISSUE THREAD

**Issue by tv-openbig** [OCA/l10n-germany#51]
If i create a tax statement with values from 2019 and select "2019" in the field version i get a statement with line formats from the version 2018. 

This would be correct if we would create a tax statement for account moves from 2018, however some lines do not match the right format for 2019:

Line 51: instead of "EDITABLE_DISPLAY" -> "TOTAL_DISPLAY"
Line 52: instead of "EDITABLE_DISPLAY" -> "GROUP_DISPLAY"
Line 53: remove from "TOTAL_DISPLAY"
Line 54: instead of "GROUP_DISPLAY" -> "TAX_DISPLAY"
Line 60: remove from "TAX_DISPLAY" & add to "TOTAL_DISPLAY"
Line 62: remove from "TOTAL_DISPLAY"
Line 63: instead of "GROUP_DISPLAY" -> TAX_DISPLAY"

<img width="996" alt="Bildschirmfoto 2019-08-19 um 10 25 16" src="https://user-images.githubusercontent.com/8348598/63252688-8aa97d80-c270-11e9-87ae-1548a23b09ea.png">

I assume we also needs to have format settings for both versions ("2018" and "2019").

Furthermore as we now have "version" to create the report, we should change the follwoing string (line 65-67 in l10n_de_tax_statement.py):
    tax_total = fields.Monetary(
        compute='_compute_tax_total',
        string='Verbl. Ust.-Vorauszahlung (66 - 67)' 

to

    tax_total = fields.Monetary(
        compute='_compute_tax_total',
        string='Verbl. Ust.-Vorauszahlung' 

And finally due to latest source code changes the translations needs an update 
(i will do that for sure)

**Comment by astirpe** [comment]
@tv-openbig could you check https://github.com/OCA/l10n-germany/pull/52 ?

**Comment by tv-openbig** [comment]
@astirpe I have reviewed and tested your changes in order to have a versioned format. There was a tiny modification required. Now it looks good on my test instance. I will merge your PR.

**Comment by astirpe** [comment]
@tv-openbig Thanks! I'm going to backport the developments made for 2019 version to V11.
