### ISSUE TITLE
README.rst outdated?

### ISSUE THREAD

**Issue by mowny** [OCA/l10n-germany#61]
module: l10n_de_tax_statement
version: 12.0

**Steps to reproduce**
- Read README.rst and rely on the description there

**Current behavior**
There is no "Invoicing" (was that the name of the higher-level app in Odoo 11?), only "Accounting".
Though the module says it is installed, I can't find the menu entries it's supposed to insert.

**Expected behavior**
Find new menu entry at Accounting -> Reporting > Germany > German Tax Statement (USt VA / Umsatzsteuervoranmeldung), where l10n_de_skr04_reports used to put its menu entry.

Edit: Okay, a few reloads later I _did_ find the new entries at Accounting -> Reporting -> Taxes Balance -> Taxes Balance _and_ Ust-Voranmeldung (which should be German Tax Statement when in English), and at Accounting -> Configuration > Accounting > German Tax Tags. I can now get data out of Taxes Balance that looks good, but Ust-Voranmeldung tosses everything into Code 21. This is no improvement to the l10n_de_reports Umsatzsteuervoranmeldung, which does exactly the same. Does this module here even improve anything or is it just duplicate content made obsolete by v12?

**Comment by tv-openbig** [comment]
I can't recapture your issue. Please be more precise or describe the test case better in order to recapture your issue.
