### ISSUE TITLE
[11.0]Date Range issue l10n_de_skr03_mis_reports

### ISSUE THREAD

**Issue by patel1008b** [OCA/l10n-germany#62]
Create 2 date ranges 1. 2018 and 2. 2019

Generate a balance sheet report for 2019.

You will find "0410 Geschäftsausstattung" wrong value, as it contains 2018 entries as well.

**Comment by patel1008b** [comment]
@OSevangelist @fkantelberg @daramousk @pedrobaeza

**Comment by patel1008b** [comment]
@OSevangelist @fkantelberg @daramousk @pedrobaeza @tv-openbig  @astirpe

**Comment by tv-openbig** [comment]
@bhaveshselarka That's in the nature of the account type as the balance of that account will be forwarded from one year (2018) to the next (2019). You can see that better if you would install in parallel the OCA module account_financial_report ("Trial Balance").

If you would select the date_range "2019" in this "Trial Balance" report you can see in the column "Initial balance" the balance from "2018".

Furthermore you could try to simulate the same with account "8400" (type "Income"). In that case you won't see the value from "2018" in "2019". That is also in the nature of both account types income / expense, which doesn't carry on the balances of prior years. 

Please give a short feedback, if that answer solves your problem.

**Comment by patel1008b** [comment]
hi, @tv-openbig thanks a lot for your response. I will try as per suggestions and share feedback here soon.
