### ISSUE TITLE
Wrong sign in tax statement line 35 and probably 36

### ISSUE THREAD

**Issue by Guenzn** [OCA/l10n-germany#73]
After Germany temporarily lowered the VAT from 19% / 7% to 16% / 5%, I noticed that the sign at column tax in line 35 is wrong. The same should probably also apply to line 36, since the taxes were not calculated by percentage in the "_finalize_lines_2019" method.

https://github.com/OCA/l10n-germany/blob/3ccf97a413f6d3f07e4d916eaa706f06d7b88a75/l10n_de_tax_statement/models/l10n_de_tax_statement_2019.py#L259

**Comment by Guenzn** [comment]
![image](https://user-images.githubusercontent.com/24382867/90401010-a622b080-e09d-11ea-80ce-57d4a7f73989.png)

**Comment by Guenzn** [comment]
@tv-openbig @astirpe

**Comment by astirpe** [comment]
@Guenzn I think you are right but I would prefer a review from someone more expert than me :sweat_smile: 

@tv-openbig I think you are the best to answer here :+1:

**Comment by Guenzn** [comment]
I will provide a PR with the fix for @tv-openbig in a minute.

**Comment by Guenzn** [comment]
@tv-openbig Our accountant has validated the tax statement report after the fix (see PR) and confirmed it as correct.
Can somebody please help with the codecov test result.
